import Link from "next/link"
import PublicLayout from "../../main/presentation/layouts/public-layout/public-layout"
import ThemeRegistry from "../../main/presentation/components/ThemeRegistry/ThemeRegistry"
import { PayPalScriptProvider } from "@paypal/react-paypal-js"

export const metadata = {
  title: 'Home Broke',
  description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      
        <html lang="en">
          
          <body>
            <ThemeRegistry>
              <PublicLayout />
              {children}
            </ThemeRegistry>
          </body>
        </html>
    )
  }
